services:
  - type: web
    name: scam-detector-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: VIRUSTOTAL_API_KEY
        sync: false
      - key: NUMVERIFY_API_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false
      - key: IMGBB_API_KEY
        sync: false
